import { useEffect, useState } from "react";
import { useInfiniteQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useLocation, useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { announcementService, localizedApiError } from "@lifewood/api-client";
import type { AnnouncementDocument, AnnouncementInput, SupportedLocale } from "@lifewood/domain";
import { SettingsTabs } from "./SettingsTabs";
import { ModalFrame } from "./ModalFrame";
import { useConfirm } from "./useConfirm";
import "./announcements.css";
const noticeTitle=(content:AnnouncementInput,locale:SupportedLocale)=>content.title ?? (locale==="en-US"?content.titleEn:content.titleZh) ?? "";
const noticeBody=(content:AnnouncementInput,locale:SupportedLocale)=>content.body ?? (locale==="en-US"?content.bodyEn:content.bodyZh) ?? "";
export type NoticeEditor = { id: string; content: AnnouncementInput; organizations: Record<string,string> };
const empty = (): NoticeEditor => ({id:crypto.randomUUID().replaceAll("-",""),organizations:{},content:{title:"",body:"",placement:"personal",audience:"all",languages:[],organizationIds:[],displayDays:30,startsAt:null,endsAt:null,version:0}});
export function AnnouncementsPage({locale}:{locale:SupportedLocale}) {
 const {t}=useTranslation();const confirm=useConfirm();const client=useQueryClient();const navigate=useNavigate();const location=useLocation();
 const [editor,setEditor]=useState<NoticeEditor|undefined>(()=>(location.state as {announcementEditor?:NoticeEditor}|null)?.announcementEditor);
 const [preview,setPreview]=useState(false);const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [placement,setPlacement]=useState("");
 useEffect(()=>{if(location.state?.announcementEditor)navigate(location.pathname,{replace:true,state:null});},[]);
 const list=useInfiniteQuery({queryKey:["admin-announcements",search,status,placement],initialPageParam:undefined as number|undefined,queryFn:({pageParam})=>announcementService.list(search,pageParam,status,placement),getNextPageParam:p=>p.nextCursor??undefined});
 const save=useMutation({mutationFn:(e:NoticeEditor)=>announcementService.save(e.id,{...e.content,displayDays:e.content.displayDays??30,startsAt:null,endsAt:null}),onSuccess:()=>{setEditor(undefined);void client.invalidateQueries({queryKey:["admin-announcements"]});}});
 const change=useMutation({mutationFn:({d,action}:{d:AnnouncementDocument;action:"publish"|"withdraw"})=>announcementService.transition(d.id,d.version,action),onSuccess:()=>client.invalidateQueries({queryKey:["admin-announcements"]})});
 const remove=useMutation({mutationFn:(d:AnnouncementDocument)=>announcementService.deleteDraft(d.id,d.version),onSuccess:()=>client.invalidateQueries({queryKey:["admin-announcements"]})});
 const publishPreview=useMutation({mutationFn:(d:AnnouncementDocument)=>announcementService.preview(d.id,d.version),onSuccess:async(result,d)=>{const audience=result.count==null?t("announcements.publicEstimate"):t("announcements.estimate",{count:result.count});if(await confirm(`${noticeTitle(d.content,locale)}\n\n${audience}\n${t("announcements.estimateHint")}\n\n${t("announcements.publishConfirm")}`,false))change.mutate({d,action:"publish"});}});
 const busy=change.isPending||remove.isPending||publishPreview.isPending;
 const update=(patch:Partial<AnnouncementInput>)=>setEditor(e=>e?{...e,content:{...e.content,...patch}}:e);
 const open=(d?:AnnouncementDocument)=>{save.reset();setPreview(false);setEditor(d?{id:d.status==="draft"?d.id:crypto.randomUUID().replaceAll("-",""),content:{...d.content,displayDays:d.content.displayDays??30,...(d.status==="draft"?{}:{title:noticeTitle(d.content,locale),body:noticeBody(d.content,locale)}),version:d.status==="draft"?d.version:0,startsAt:d.status==="draft"?d.content.startsAt:null,endsAt:d.status==="draft"?d.content.endsAt:null},organizations:{}}:empty());};
 const close=async()=>{if(!save.isPending && await confirm(t("announcements.unsaved"),false))setEditor(undefined);};
 const error=save.error??change.error??remove.error??publishPreview.error??list.error;
 return <main className="content announcement-admin"><SettingsTabs locale={locale}/>
 <section className="page-toolbar"><input type="search" aria-label={t("announcements.search")} placeholder={t("announcements.search")} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={t("announcements.status")} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t("announcements.allStatuses")}</option>{["draft","published","withdrawn"].map(value=><option key={value} value={value}>{t(`announcements.${value}`)}</option>)}</select><select aria-label={t("announcements.placement")} value={placement} onChange={e=>setPlacement(e.target.value)}><option value="">{t("announcements.allPlacements")}</option>{["login","personal"].map(value=><option key={value} value={value}>{t(`announcements.${value}`)}</option>)}</select><button onClick={()=>{remove.reset();publishPreview.reset();change.reset();void list.refetch();}}>{t("announcements.refresh")}</button><button className="primary push-right" onClick={()=>open()}>{t("announcements.new")}</button></section>
 {error && !editor && <div role="alert" className="message error">{localizedApiError(error,t)}</div>}
 <section className="table-card"><div className="management-table-scroll"><table><thead><tr><th>{t("announcements.title")}</th><th>{t("announcements.audience")}</th><th>{t("announcements.status")}</th><th>{t("announcements.recipients")}</th><th>{t("announcements.actions")}</th></tr></thead><tbody>
 {list.data?.pages.flatMap(p=>p.items).map(d=><tr key={d.id}><td data-label={t("announcements.title")}><strong>{noticeTitle(d.content,locale)}</strong><small>{t(`announcements.${d.content.placement}`)}</small></td><td data-label={t("announcements.audience")}>{t(`announcements.${d.content.audience}`)}<small>{d.content.languages.join(" · ")}{d.content.organizationIds.length>0?` · ${t("announcements.organizations")} (${d.content.organizationIds.length})`:""}</small></td><td data-label={t("announcements.status")}>{t(`announcements.${d.status}`)}</td><td data-label={t("announcements.recipients")}>{d.content.placement==="personal"?d.recipients:"—"}</td><td data-label={t("announcements.actions")}><div className="notice-actions"><button onClick={()=>open(d)}>{t(d.status==="draft"?"announcements.edit":"announcements.copy")}</button>{d.status!=="withdrawn"&&<button disabled={busy} onClick={async()=>{if(d.status==="draft"){publishPreview.mutate(d);return;}if(await confirm(t("announcements.withdrawConfirm"),true))change.mutate({d,action:"withdraw"});}}>{t(d.status==="draft"?"announcements.publish":"announcements.withdraw")}</button>}{d.status==="draft"&&<button className="danger" disabled={busy} onClick={async()=>{if(await confirm(t("announcements.deleteConfirm",{title:noticeTitle(d.content,locale)}),true))remove.mutate(d);}}>{t("announcements.deleteDraft")}</button>}</div></td></tr>)}
 </tbody></table>{list.isPending&&<p role="status">{t("announcements.loading")}</p>}{list.data?.pages[0].items.length===0&&<p className="empty">{t("announcements.empty")}</p>}</div>{list.hasNextPage&&<button disabled={list.isFetchingNextPage} onClick={()=>void list.fetchNextPage()}>{t("announcements.more")}</button>}</section>
 {editor&&<ModalFrame labelledBy="notice-editor-title" className="notice-editor" busy={save.isPending} onClose={()=>void close()}><form onSubmit={e=>{e.preventDefault();save.mutate(editor);}}><h2 id="notice-editor-title">{t("announcements.edit")}</h2>
 <fieldset disabled={save.isPending} className="notice-form"><div className="notice-pair"><label>{t("announcements.placement")}<select value={editor.content.placement} onChange={e=>update({placement:e.target.value as "login"|"personal",organizationIds:[],audience:"all",languages:[]})}><option value="personal">{t("announcements.personal")}</option><option value="login">{t("announcements.login")}</option></select></label><label>{t("announcements.audience")}<select value={editor.content.audience} onChange={e=>update({audience:e.target.value as "all"|"specified",languages:[],organizationIds:[]})}><option value="all">{t("announcements.all")}</option><option value="specified">{t("announcements.specified")}</option></select></label></div>
 <p className="muted">{t(editor.content.placement==="login"?"announcements.publicHint":"announcements.snapshotHint")}</p>
 {editor.content.audience==="specified"&&<section className="notice-target"><strong>{t("announcements.languages")}</strong><div className="notice-actions">{["zh-CN","en-US"].map(l=><label key={l}><input type="checkbox" checked={editor.content.languages.includes(l)} onChange={e=>update({languages:e.target.checked?[...editor.content.languages,l]:editor.content.languages.filter(x=>x!==l)})}/>{l==="zh-CN"?"简体中文":"English"}</label>)}</div>{editor.content.placement==="personal"&&<><strong>{t("announcements.organizations")}</strong><p>{editor.content.organizationIds.map(id=>editor.organizations[id]).filter(Boolean).join(" · ") || (editor.content.organizationIds.length ? `${t("announcements.selected")} · ${editor.content.organizationIds.length}` : "")||t("announcements.noSelection")}</p><div className="notice-actions"><button type="button" onClick={()=>navigate(`/${locale}/organizations?pick=announcement`,{state:{announcementEditor:editor}})}>{t("announcements.chooseOrgs")}</button><button type="button" onClick={()=>update({organizationIds:[]})}>{t("announcements.clear")}</button></div></>}<p className="muted">{t("announcements.scopeHint")}</p></section>}
 <section className="notice-copy-fields"><label>{t("announcements.contentTitle")}<input required maxLength={160} value={noticeTitle(editor.content,locale)} onChange={e=>update({title:e.target.value,body:noticeBody(editor.content,locale)})}/></label><label>{t("announcements.contentBody")}<textarea required maxLength={12000} rows={8} value={noticeBody(editor.content,locale)} onChange={e=>update({title:noticeTitle(editor.content,locale),body:e.target.value})}/></label><p className="muted">{t("announcements.singleContentHint")}</p>{editor.content.titleZh != null && editor.content.titleEn != null && <p className="muted">{t("announcements.legacyContentHint")}</p>}</section>
 <label className="notice-duration">{t("announcements.displayDays")}<input type="number" inputMode="numeric" required min={1} max={3650} step={1} value={editor.content.displayDays??""} onChange={e=>update({displayDays:e.target.value===""?null:Number(e.target.value)})}/></label><p className="muted">{t("announcements.displayDaysHint")}</p>
 </fieldset>{save.error&&<p role="alert" className="message error">{localizedApiError(save.error,t)}</p>}
 <div className="notice-actions"><button type="button" disabled={save.isPending} onClick={()=>setPreview(!preview)}>{t("announcements.preview")}</button><button type="button" disabled={save.isPending} onClick={()=>void close()}>{t("announcements.cancel")}</button><button className="primary" disabled={save.isPending}>{t(save.isPending?"announcements.loading":"announcements.save")}</button></div>
 {preview&&<article className="notice-preview"><h3>{noticeTitle(editor.content,locale)}</h3><p>{noticeBody(editor.content,locale)}</p></article>}
 </form></ModalFrame>}</main>;
}
