import {useState} from "react";
import {useQuery,useMutation,useQueryClient} from "@tanstack/react-query";
import {Link,useSearchParams} from "react-router-dom";
import {useTranslation} from "react-i18next";
import {invitationService,localizedApiError} from "@lifewood/api-client";
import type {SupportedLocale} from "@lifewood/domain";
import {loadAllOrganizations} from "./organization-loader";
import {useConfirm} from "./useConfirm";
import {ModalFrame} from "./ModalFrame";
import {HelpPopover} from "./HelpPopover";
import "./invitations.css";
export function InvitationsPage({locale}:{locale:SupportedLocale}) {
 const confirm=useConfirm();
 const [publicUrl,setPublicUrl]=useState("");
 const {t}=useTranslation(),client=useQueryClient(),[params,setParams]=useSearchParams();
 const search=params.get("q")??"",status=params.get("status")??"",org=params.get("organization")??"",page=Math.max(1,Number(params.get("page"))||1);
 const [creating,setCreating]=useState(false),[secret,setSecret]=useState(""),[copied,setCopied]=useState(""),[memberId,setMemberId]=useState(""),[memberPage,setMemberPage]=useState(1),[error,setError]=useState<unknown>();
 const organizations=useQuery({queryKey:["admin-organizations","user-selector"],queryFn:()=>loadAllOrganizations()});
 const list=useQuery({queryKey:["admin-invitations",search,status,org,page],queryFn:()=>invitationService.list(search,status,org,page),refetchInterval:30000});
 const members=useQuery({queryKey:["invitation-members",memberId,memberPage],queryFn:()=>invitationService.members(memberId,memberPage),enabled:!!memberId});
 const mutation=useMutation({mutationFn:invitationService.create,onSuccess:async data=>{setCreating(false);setSecret(data.code);setPublicUrl(data.publicUrl??"");setCopied("");await client.invalidateQueries({queryKey:["admin-invitations"]});}});
 const action=useMutation({mutationFn:async({id,disable}:{id:string;disable:boolean})=>{if(disable){await invitationService.disable(id);await client.invalidateQueries({queryKey:["admin-invitations"]});}else{const data=await invitationService.reveal(id);setSecret(data.code);setPublicUrl(data.publicUrl??"");setCopied("");}},onError:setError});
 const filter=(key:string,value:string)=>setParams(current=>{const p=new URLSearchParams(current);value?p.set(key,value):p.delete(key);if(key!=="page")p.delete("page");return p;});
 const date=(value:number)=>new Date(value*1000).toLocaleString(locale);
 return <main className="content pagination-layout invitation-page">
 <div className="page-toolbar invitation-toolbar">
 <form key={search} role="search" onSubmit={e=>{e.preventDefault();filter("q",String(new FormData(e.currentTarget).get("q")??"").trim());}}><input name="q" type="search" maxLength={160} defaultValue={search} aria-label={t("invitation.search")} placeholder={t("invitation.search")}/><button>{t("common.search")}</button></form>
 <select aria-label={t("invitation.organization")} value={org} onChange={e=>filter("organization",e.target.value)}><option value="">{t("invitation.allOrgs")}</option>{organizations.data?.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>
 <select aria-label={t("invitation.status")} value={status} onChange={e=>filter("status",e.target.value)}><option value="">{t("invitation.all")}</option>{["active","used","expired","disabled"].map(s=><option key={s} value={s}>{t("invitation.states."+s)}</option>)}</select>
 <button disabled={list.isFetching} onClick={()=>void list.refetch()}>{t("invitation.refresh")}</button><button className="primary" disabled={!organizations.data} onClick={()=>{mutation.reset();setCreating(true);}}>{t("invitation.create")}</button><HelpPopover label={t("invitation.title")}>{t("invitation.help")}</HelpPopover>
 {(search||org||status)&&<button onClick={()=>setParams({})}>{t("invitation.clear")}</button>}</div>
 {(list.error||error||organizations.error)&&<p role="alert">{localizedApiError(list.error??error??organizations.error,t)}</p>}
 <section className="invitation-surface pagination-layout pagination-surface"><div className="pagination-scroll">
 {list.isPending?<p role="status">{t("common.loading")}</p>:<table><thead><tr>{["organization","note","code","creator","created","expires","usage","status","actions"].map(x=><th key={x}>{t("invitation."+x)}</th>)}</tr></thead><tbody>{list.data?.items.map(i=><tr key={i.id}><td>{i.organization||"—"}</td><td>{i.note||"—"}</td><td><code>•••• {i.suffix}</code></td><td>{i.creator||"—"}</td><td>{date(i.createdAt)}</td><td>{date(i.expires)}</td><td>{i.used} / {i.limit}</td><td>{t("invitation.states."+i.status)}</td><td><div className="invitation-row-actions"><button onClick={()=>{setMemberId(i.id);setMemberPage(1);}}>{t("invitation.records")}</button>{i.status==="active"&&<><button disabled={action.isPending} onClick={()=>action.mutate({id:i.id,disable:false})}>{t("invitation.reveal")}</button><button disabled={action.isPending} onClick={async()=>{if(await confirm(t("invitation.disableConfirm")))action.mutate({id:i.id,disable:true});}}>{t("invitation.disable")}</button></>}</div></td></tr>)}</tbody></table>}
 {list.data&&!list.data.items.length&&<p className="empty">{t("invitation.empty")}</p>}</div>
 <footer className="pager pagination-footer"><span>{t("invitation.page",{page:list.data?.page??page,count:list.data?.total??0})}</span><button disabled={list.isFetching||!list.data||list.data.page<=1} onClick={()=>filter("page",String((list.data?.page??page)-1))}>{t("invitation.previous")}</button><button disabled={list.isFetching||!list.data||list.data.page*list.data.pageSize>=list.data.total} onClick={()=>filter("page",String((list.data?.page??page)+1))}>{t("invitation.nextPage")}</button></footer></section>
 {creating&&<ModalFrame labelledBy="invitation-create" busy={mutation.isPending} onClose={()=>setCreating(false)}><h2 id="invitation-create">{t("invitation.create")}</h2><form className="invitation-form" onSubmit={e=>{e.preventDefault();if(mutation.isPending)return;const f=new FormData(e.currentTarget);mutation.mutate({organizationId:String(f.get("organization")),note:String(f.get("note")),days:Number(f.get("days")),limit:Number(f.get("limit"))});}}>
 <label>{t("invitation.organization")}<select name="organization" required defaultValue={org}><option value="">{t("invitation.chooseOrg")}</option>{organizations.data?.filter(o=>o.active).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
 <label>{t("invitation.note")}<input name="note" maxLength={100}/></label><div className="invitation-form-pair"><label>{t("invitation.days")}<input name="days" type="number" min={1} max={90} defaultValue={7} required/></label><label>{t("invitation.limit")}<input name="limit" type="number" min={1} max={100} defaultValue={1} required/></label></div>
 {mutation.error&&<p role="alert">{localizedApiError(mutation.error,t)}</p>}<footer><button type="button" disabled={mutation.isPending} onClick={()=>setCreating(false)}>{t("invitation.cancel")}</button><button className="primary" disabled={mutation.isPending}>{t("invitation.save")}</button></footer></form></ModalFrame>}
 {secret&&<ModalFrame labelledBy="invitation-secret" onClose={()=>setSecret("")}><h2 id="invitation-secret">{t("invitation.code")}</h2><input className="invitation-secret" aria-label={t("invitation.code")} readOnly value={secret}/><p role="status">{copied}</p><div className="invitation-row-actions"><button onClick={()=>void navigator.clipboard.writeText(secret).then(()=>setCopied(t("invitation.copied"))).catch(()=>setCopied(t("invitation.copyFailed")))}>{t("invitation.copy")}</button>{publicUrl&&<button onClick={()=>void navigator.clipboard.writeText(`${publicUrl.replace(/\/$/,"")}/${locale}/register#code=${encodeURIComponent(secret)}`).then(()=>setCopied(t("invitation.copied"))).catch(()=>setCopied(t("invitation.copyFailed")))}>{t("invitation.copyLink")}</button>}<button onClick={()=>setSecret("")}>{t("invitation.close")}</button></div></ModalFrame>}
 {memberId&&<ModalFrame labelledBy="invitation-members" onClose={()=>setMemberId("")}><h2 id="invitation-members">{t("invitation.records")}</h2>{members.isPending?<p role="status">{t("common.loading")}</p>:members.error?<p role="alert">{localizedApiError(members.error,t)}</p>:<><div className="invitation-member-list">{members.data?.items.map(m=><div key={m.id}>{m.name?<Link to={`/${locale}/users?q=${encodeURIComponent(m.email)}`}><img width="32" height="32" src={`/api/admin/users/${m.id}/avatar`} alt=""/><span>{m.name}<small>{m.email}</small></span></Link>:<span>{t("invitation.closed")}</span>}<time>{date(m.joinedAt)}</time></div>)}{!members.data?.items.length&&<p>{t("invitation.noMembers")}</p>}</div><footer className="pager"><button disabled={memberPage<=1} onClick={()=>setMemberPage(p=>p-1)}>{t("invitation.previous")}</button><span>{t("invitation.page",{page:members.data?.page??memberPage,count:members.data?.total??0})}</span><button disabled={!members.data||members.data.page*members.data.pageSize>=members.data.total} onClick={()=>setMemberPage(p=>p+1)}>{t("invitation.nextPage")}</button></footer></>}<button onClick={()=>setMemberId("")}>{t("invitation.close")}</button></ModalFrame>}
 </main>;
}
