import { HelpPopover } from "@lifewood/ui/help-popover";
import {useState} from "react";
import {useQuery,useInfiniteQuery,useMutation,useQueryClient} from "@tanstack/react-query";
import {useParams} from "react-router-dom";
import {useTranslation} from "react-i18next";
import {notificationService as service,authService,localizedApiError,type NotificationRule} from "@lifewood/api-client";
import {NoticeModal} from "@lifewood/ui/notifications";
import {SettingsTabs} from "./SettingsTabs";
export function NotificationSettingsPage(){const {locale:raw}=useParams();const locale=raw==="en-US"?"en-US":"zh-CN";const {t}=useTranslation();const client=useQueryClient();const [editing,setEditing]=useState<NotificationRule>();const [days,setDays]=useState<number>();const rules=useQuery({queryKey:["notification-rules"],queryFn:service.rules});const user=useQuery({queryKey:["admin-me"],queryFn:authService.getCurrentUser});const owner=user.data?.roles.includes("owner");const logs=useInfiniteQuery({queryKey:["notification-logs"],queryFn:({pageParam})=>service.logs(pageParam),initialPageParam:undefined as number|undefined,getNextPageParam:p=>p.nextCursor??undefined,enabled:owner,refetchInterval:30000});const save=useMutation({mutationFn:service.saveRule,onSuccess:()=>{setEditing(undefined);void client.invalidateQueries({queryKey:["notification-rules"]});void client.invalidateQueries({queryKey:["notification-catalog"]});}});const retention=useMutation({mutationFn:service.retention,onSuccess:()=>client.invalidateQueries({queryKey:["notification-rules"]})});const retry=useMutation({mutationFn:service.retry,onSuccess:()=>client.invalidateQueries({queryKey:["notification-logs"]})});const error=rules.error??save.error??retention.error??logs.error??retry.error;
return <main className="content"><SettingsTabs locale={locale}/>{error&&<p role="alert">{localizedApiError(error,t)}</p>}<div className="notification-toolbar"><div className="field-help-heading"><label>{t("notifications.retention")}<input type="number" min={30} max={3650} step={1} value={days??rules.data?.retentionDays??365} onChange={e=>setDays(Number(e.target.value))}/></label><HelpPopover label={t("notifications.retention")}>{t("notifications.retentionHint")}</HelpPopover></div><button disabled={retention.isPending} onClick={()=>retention.mutate(days??rules.data?.retentionDays??365)}>{t("notifications.save")}</button><button onClick={()=>{void rules.refetch();if(owner)void logs.refetch();}}>{t("notifications.refresh")}</button></div><section className="notification-rule-list">{rules.data?.items.map(r=><article key={r.kind}><strong>{t(`notifications.kinds.${r.kind}`)}</strong><p>{t(r.enabled?"notifications.enabled":"notifications.disabled")} · {t(`notifications.levels.${r.level}`)}</p><p>{(locale==="en-US"?r.titleEn:r.titleZh).replace("{project}",t("notifications.exampleProject")).replace("{actor}",t("notifications.exampleActor"))}</p><button onClick={()=>{save.reset();setEditing({...r});}}>{t("notifications.edit")}</button></article>)}</section>
{owner&&<section><h2>{t("notifications.deliveryLogs")}</h2><p>{t("notifications.queueCounts",{pending:logs.data?.pages[0].pending??0,failed:logs.data?.pages[0].failed??0})}</p><ul className="notification-list">{logs.data?.pages.flatMap(p=>p.items).map(l=><li key={l.id}><div><strong>{t(`notifications.kinds.${l.kind}`)}</strong><p>{new Date(l.createdAt).toLocaleString(locale)} · {t(`notifications.deliveryStates.${l.status}`)} · {t("notifications.deliveryCount",{count:l.recipients,attempts:l.attempts})}</p>{l.error&&<p>{t("notifications.storageFailure")}</p>}{l.status==="failed"&&<button disabled={retry.isPending} onClick={()=>retry.mutate(l.id)}>{t("common.retry")}</button>}</div></li>)}</ul>{logs.hasNextPage&&<button onClick={()=>void logs.fetchNextPage()}>{t("notifications.more")}</button>}</section>}
{editing&&<NoticeModal title={t("notifications.editRule")} onClose={()=>!save.isPending&&setEditing(undefined)}><form className="notification-form" onSubmit={e=>{e.preventDefault();save.mutate(editing);}}><label><input type="checkbox" disabled={editing.kind==="feedback_reply"} checked={editing.enabled} onChange={e=>setEditing({...editing,enabled:e.target.checked})}/>{t("notifications.enabled")}</label><label>{t("notifications.titleZh")}<textarea required maxLength={300} value={editing.titleZh} onChange={e=>setEditing({...editing,titleZh:e.target.value})}/></label><label>{t("notifications.titleEn")}<textarea required maxLength={300} value={editing.titleEn} onChange={e=>setEditing({...editing,titleEn:e.target.value})}/></label><HelpPopover label={t("notifications.editRule")}>{t("notifications.templateHint")}</HelpPopover><output>{editing.titleZh.replace("{project}",t("notifications.exampleProject")).replace("{actor}",t("notifications.exampleActor"))}<br/>{editing.titleEn.replace("{project}",t("notifications.exampleProject")).replace("{actor}",t("notifications.exampleActor"))}</output><label>{t("notifications.level")}<select value={editing.level} onChange={e=>setEditing({...editing,level:e.target.value})}>{["normal","important","action"].map(l=><option key={l} value={l}>{t(`notifications.levels.${l}`)}</option>)}</select></label><div className="field-help-heading"><label>{t("notifications.audience")}<select disabled={editing.audience==="owners"||editing.kind==="feedback_reply"} value={editing.audience} onChange={e=>setEditing({...editing,audience:e.target.value})}>{editing.audience==="owners"&&<option value="owners">{t("notifications.owners")}</option>}<option value="responsible">{t(editing.kind==="feedback_reply"?"feedback.author":"notifications.responsible")}</option><option value="allAdmins">{t("notifications.allAdmins")}</option></select></label><HelpPopover label={t("notifications.audience")}>{t(editing.kind==="feedback_reply"?"feedback.deliveryRuleHint":editing.audience==="owners"?"notifications.backupAudienceHint":"notifications.audienceHint")}</HelpPopover></div><label><input type="checkbox" disabled={editing.kind==="feedback_reply"} checked={editing.allowMute} onChange={e=>setEditing({...editing,allowMute:e.target.checked})}/>{t("notifications.allowMute")}</label>{save.error&&<p role="alert">{t("notifications.ruleConflict")}</p>}<button disabled={save.isPending}>{t("notifications.save")}</button></form></NoticeModal>}
</main>;
}
