using Lifewood.PlatformApi.Contracts;
using Lifewood.PlatformApi.Persistence;
using Microsoft.Data.Sqlite;
using Xunit;
namespace Lifewood.PlatformApi.Tests;
public sealed class AnnouncementTests:IDisposable {
 private readonly string root=Path.Combine(Path.GetTempPath(),"lw-announcements-"+Guid.NewGuid().ToString("N"));
 private readonly string connection;private readonly AnnouncementRepository repo;
 public AnnouncementTests(){Directory.CreateDirectory(root);connection="Data Source="+Path.Combine(root,"test.db")+";Pooling=False";Sql("CREATE TABLE users(id TEXT,locale TEXT,organization_id TEXT,is_active INTEGER);CREATE TABLE organizations(id TEXT,is_active INTEGER);INSERT INTO organizations VALUES('a',1),('b',1);INSERT INTO users VALUES('one','zh-CN','a',1),('two','en-US','a',1),('three','zh-CN','b',1),('four',NULL,'a',1),('disabled','zh-CN','a',0);");repo=new(connection);repo.Initialize();}
 private void Sql(string sql){using var db=new SqliteConnection(connection);db.Open();using var c=db.CreateCommand();c.CommandText=sql;c.ExecuteNonQuery();}
 private static AnnouncementInput Input()=>new("公告","正文","Notice","Body","personal","specified",["zh-CN"],["a"],null,null);
 private AnnouncementDocument Publish(AnnouncementInput? input=null){var id=Guid.NewGuid().ToString("N");Assert.Null(repo.Save(id,input??Input(),out var d));Assert.Null(repo.Transition(id,d!.Version,true,out d));return d!;}
 [Fact] public void RecipientsAreAnIntersectionAndHistoryIsPrivateAndStable(){var d=Publish();Assert.Equal(2,d.Recipients);Assert.Single(repo.Feed("one","zh-CN",null).Items);Assert.Single(repo.Feed("four","zh-CN",null).Items);Assert.Empty(repo.Feed("two","zh-CN",null).Items);Assert.Empty(repo.Feed("three","zh-CN",null).Items);Assert.Empty(repo.Feed("disabled","zh-CN",null).Items);Assert.Empty(repo.Feed(null,"zh-CN",null).Items);Assert.False(repo.Dismiss("two",d.Id));Sql("UPDATE users SET locale='en-US',organization_id='b' WHERE id='one';INSERT INTO users VALUES('new','zh-CN','a',1);");Assert.Single(repo.Feed("one","en-US",null).Items);Assert.Empty(repo.Feed("new","zh-CN",null).Items);Assert.True(repo.Dismiss("one",d.Id));var restarted=new AnnouncementRepository(connection);Assert.Empty(restarted.Feed("one","zh-CN",null,true).Items);Assert.True(Assert.Single(restarted.Feed("one","zh-CN",null).Items).Dismissed);}
 [Fact] public void PagingDoesNotMixAccountsOrDuplicateNewArrivals(){for(var i=0;i<23;i++)Publish();var first=repo.Feed("one","zh-CN",null);Assert.Equal(20,first.Items.Length);Publish();var second=repo.Feed("one","zh-CN",first.NextCursor);Assert.Equal(3,second.Items.Length);Assert.Empty(first.Items.Select(x=>x.Id).Intersect(second.Items.Select(x=>x.Id)));Assert.Empty(repo.Feed("three","zh-CN",null).Items);}
 [Fact] public void PublicLanguageSchedulingAndWithdrawalAreEnforced(){var d=Publish(Input() with {Placement="login",OrganizationIds=[]});Assert.Single(repo.Feed(null,"zh-CN",null).Items);Assert.Empty(repo.Feed(null,"en-US",null).Items);Assert.Null(repo.Transition(d.Id,d.Version,false,out _));Assert.Empty(repo.Feed(null,"zh-CN",null).Items);Publish(Input() with {StartsAt=DateTimeOffset.UtcNow.AddDays(1).ToString("O")});Assert.Empty(repo.Feed("one","zh-CN",null).Items);}
 [Fact] public void ValidationAndOptimisticVersionsProtectPublishedContent(){var id=Guid.NewGuid().ToString("N");Assert.Equal("invalid",repo.Save(id,Input() with {Placement="login"},out _));Assert.Equal("invalid",repo.Save(id,Input() with {Audience="specified",Languages=[],OrganizationIds=[]},out _));Assert.Equal("invalid",repo.Save(id,Input() with {EndsAt="bad date"},out _));Assert.Null(repo.Save(id,Input(),out var draft));Assert.Equal("conflict",repo.Save(id,Input(),out _));Assert.Null(repo.Transition(id,draft!.Version,true,out var published));Assert.Equal("conflict",repo.Save(id,Input() with {Version=published!.Version},out _));Assert.Equal("conflict",repo.Transition(id,draft.Version,false,out _));}
 [Fact] public void BulkDismissOnlyChangesTheCallingAccountsReceipts(){var a=Publish();var b=Publish();Assert.True(repo.DismissMany("one",[a.Id,b.Id]));Assert.Empty(repo.Feed("one","zh-CN",null,true).Items);Assert.Equal(2,repo.Feed("four","zh-CN",null,true).Items.Length);Assert.True(repo.DismissMany("two",[a.Id]));Assert.Equal(2,repo.Feed("four","zh-CN",null,true).Items.Length);Assert.False(repo.DismissMany("one",new string[501]));}
 public void Dispose(){Directory.Delete(root,true);}
}
