using Lifewood.PlatformApi.Persistence;
using Lifewood.PlatformApi.Features;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Data.Sqlite;
using Xunit;
namespace Lifewood.PlatformApi.Tests;
public sealed class InvitationTests:IDisposable {
 private readonly string root=Path.Combine(Path.GetTempPath(),"portal-invite-"+Guid.NewGuid().ToString("N"));
 private readonly string connection,owner,org;private readonly UserRepository users;private readonly InvitationRepository invitations;private readonly EmailRepository emails;
 public InvitationTests(){Directory.CreateDirectory(root);connection="Data Source="+Path.Combine(root,"test.db")+";Pooling=False";new ProjectRepository(connection).Initialize();new RevisionStore(connection).Initialize();users=new(connection,root);users.Initialize();owner=users.CreateOwner("Owner","owner@example.test","password-123",organizationName:"Organization").User!.Id;new AdminRepository(connection).Initialize();new DeliveryRepository(connection).Initialize();var notifications=new NotificationRepository(connection);notifications.Initialize();var protector=new EphemeralDataProtectionProvider();emails=new EmailRepository(connection,protector,EmailTests.Settings(),users,notifications);emails.Initialize();invitations=new(connection,protector);invitations.Initialize();org=(string)Sql("SELECT organization_id FROM users LIMIT 1")!;}
 private object? Sql(string sql){using var c=new SqliteConnection(connection);c.Open();using var q=c.CreateCommand();q.CommandText=sql;return q.ExecuteScalar();}
 private string Code(int limit=1)=>invitations.Create(new(org,"Team onboarding",7,limit),owner)!.Code;
 [Fact]public void VerifiedRegistrationIsAtomicSingleUseAndFixedCustomerRole(){var code=Code();Assert.Equal("Organization",invitations.Lookup(code)!.Organization);var challenge=invitations.Challenge(new(code,"new@example.test","en-US"))!;Assert.Equal(1L,Sql("SELECT COUNT(*) FROM users"));Assert.Equal(0,invitations.List(null,null,null,1).Items[0].Used);Assert.True(invitations.Register(new(challenge.Token,"New member","new-password-123")));Assert.False(invitations.Register(new(challenge.Token,"Repeated","new-password-123")));Assert.Null(invitations.Lookup(code));var account=users.Authenticate("new@example.test","new-password-123");Assert.Equal(AccountLoginOutcome.Success,account.Outcome);Assert.Equal("customer",Sql("SELECT role FROM users WHERE normalized_email='NEW@EXAMPLE.TEST'"));Assert.Equal(org,Sql("SELECT organization_id FROM users WHERE normalized_email='NEW@EXAMPLE.TEST'"));Assert.Equal(1L,Sql("SELECT verified FROM email_settings WHERE email='new@example.test'"));Assert.Equal(0L,Sql("SELECT notifications FROM email_settings WHERE email='new@example.test'"));var item=invitations.List(null,null,null,1).Items[0];Assert.Equal("used",item.Status);Assert.Single(invitations.Members(item.Id,1).Items);}
 [Theory][InlineData("disabled")][InlineData("expired")][InlineData("organization")][InlineData("token")]
 public void RevocationAndExpiryAreRecheckedAtRegistration(string mode){var code=Code();var challenge=invitations.Challenge(new(code,"new@example.test","zh-CN"))!;switch(mode){case "disabled":invitations.Disable(invitations.List(null,null,null,1).Items[0].Id);break;case "expired":Sql("UPDATE invitations SET expires=0");break;case "organization":Sql("UPDATE organizations SET is_active=0");break;default:Sql("UPDATE invitation_challenges SET expires=0");break;}Assert.False(invitations.Register(new(challenge.Token,"New member","password-123")));Assert.Equal(1L,Sql("SELECT COUNT(*) FROM users"));}
 [Fact]public async Task ConcurrentLastSlotHasExactlyOneWinner(){var code=Code();var first=invitations.Challenge(new(code,"first@example.test","zh-CN"))!;var second=invitations.Challenge(new(code,"second@example.test","en-US"))!;var results=await Task.WhenAll(Task.Run(()=>invitations.Register(new(first.Token,"First member","password-123"))),Task.Run(()=>invitations.Register(new(second.Token,"Second member","password-123"))));Assert.Single(results,x=>x);Assert.Equal(1L,Sql("SELECT COUNT(*) FROM invitation_members"));Assert.Equal(2L,Sql("SELECT COUNT(*) FROM users"));}
 [Fact]public void CodesAreNotStoredInPlaintextAndSearchIsLiteral(){var code=Code();Assert.NotEqual(code,Sql("SELECT code_secret FROM invitations"));Assert.NotEqual(code,Sql("SELECT code_hash FROM invitations"));var item=invitations.List("onboarding","active",org,99).Items[0];Assert.Equal(code,invitations.Reveal(item.Id)!.Code);Assert.Equal(code[^4..],item.Suffix);Assert.Empty(invitations.List("%",null,null,1).Items);Assert.Empty(invitations.List(null,"expired",null,1).Items);invitations.Disable(item.Id);Assert.Null(invitations.Reveal(item.Id));}
 [Fact]public void ExistingAccountsCooldownAndInvalidDetailsDoNotCreateAccounts(){var code=Code(3);Assert.Null(invitations.Challenge(new(code,"owner@example.test","zh-CN")));Assert.Null(invitations.Challenge(new(code,"not an email","zh-CN")));var challenge=invitations.Challenge(new(code,"new@example.test","zh-CN"))!;Assert.Null(invitations.Challenge(new(Code(),"NEW@example.test","en-US")));Assert.False(invitations.Register(new(challenge.Token,"N","password-123")));Assert.False(invitations.Register(new(challenge.Token,"Name","short")));Assert.Equal(1L,Sql("SELECT COUNT(*) FROM users"));invitations.RevokeChallenge(challenge.Token);Assert.Null(invitations.InspectToken(challenge.Token));}
 [Fact]public async Task InvitationEmailsUseQueueAndCancelWhenInvitationIsDisabled(){var code=Code(2);var challenge=invitations.Challenge(new(code,"new@example.test","en-US"))!;emails.QueueInvitation(challenge);var item=Assert.Single(emails.QueueStatus("pending","invite",1).Items);Assert.Equal("n***@example.test",item.Recipient);var mailer=new EmailTests.FakeMailer();await emails.DeliverOne(mailer,CancellationToken.None);Assert.Single(mailer.Messages);Assert.Contains("/en-US/register#token=",mailer.Messages.Single().Body);Assert.Single(emails.QueueStatus("sent","invite",1).Items);var second=invitations.Challenge(new(code,"other@example.test","zh-CN"))!;emails.QueueInvitation(second);invitations.Disable(invitations.List(null,null,null,1).Items[0].Id);await emails.DeliverOne(mailer,CancellationToken.None);Assert.Single(mailer.Messages);Assert.Single(emails.QueueStatus("cancelled","invite",1).Items);}
 [Fact]public void NewCodesAreSixLettersUniqueAndCaseInsensitive(){var codes=Enumerable.Range(0,100).Select(_=>Code()).ToArray();Assert.Equal(100,codes.Distinct().Count());Assert.All(codes,code=>{Assert.Matches("^[A-Z]{6}$",code);Assert.NotNull(invitations.Lookup(" "+code.ToLowerInvariant()+" "));});}
 [Fact]public void PreviouslyIssuedLongCodesStillWork(){const string legacy="0123456789ABCDEF0123456789ABCDEF";Code();var hash=Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(legacy)));Sql($"UPDATE invitations SET code_hash='{hash}'");Assert.NotNull(invitations.Lookup(legacy));var challenge=invitations.Challenge(new(legacy,"legacy@example.test","en-US"))!;Assert.True(invitations.Register(new(challenge.Token,"Legacy member","password-123")));}
 [Fact]public void VerificationRestoresIdentityAndMigratesExistingChallenges(){Sql("ALTER TABLE invitation_challenges DROP COLUMN display_name");invitations.Initialize();invitations.Initialize();var code=Code();Assert.Null(invitations.Challenge(new(code,"invalid@example.test","zh-CN"," ")));var challenge=invitations.Challenge(new(code,"new@example.test","zh-CN","  My nickname  "))!;var verified=invitations.InspectToken(challenge.Token)!;Assert.Equal("My nickname",verified.DisplayName);Assert.Equal("new@example.test",verified.Email);Assert.Null(invitations.Lookup(code)!.Email);Assert.True(invitations.Register(new(challenge.Token,verified.DisplayName!,"password-123")));Assert.Null(invitations.InspectToken(challenge.Token));}
 [Fact]public void InternationalEmailUsesSameNormalizationAsLogin(){var code=Code(2);var challenge=invitations.Challenge(new(code,"person@éxample.test","en-US"))!;Assert.NotNull(challenge);Assert.Null(invitations.Challenge(new(code,"PERSON@ÉXAMPLE.TEST","en-US")));Assert.True(invitations.Register(new(challenge.Token,"Member","password-123")));Assert.Equal(AccountLoginOutcome.Success,users.Authenticate("person@éxample.test","password-123").Outcome);}
 public void Dispose(){SqliteConnection.ClearAllPools();Directory.Delete(root,true);}
}
