using System.Text.Json.Serialization;
using Lifewood.PlatformApi.Contracts;

namespace Lifewood.PlatformApi.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(CurrentUserDto))]
[JsonSerializable(typeof(HealthDto))]
[JsonSerializable(typeof(CurrentUserDto[]))]
[JsonSerializable(typeof(AuthStatusDto))]
[JsonSerializable(typeof(CsrfTokenDto))]
[JsonSerializable(typeof(BootstrapAccountRequest))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(ResetPasswordRequest))]
[JsonSerializable(typeof(AdminUserDto))]
[JsonSerializable(typeof(AdminUserDto[]))]
[JsonSerializable(typeof(PagedAdminUsersDto))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(OrganizationDto))]
[JsonSerializable(typeof(AdminOrganizationDto))]
[JsonSerializable(typeof(AdminOrganizationDto[]))]
[JsonSerializable(typeof(PagedAdminOrganizationsDto))]
[JsonSerializable(typeof(CreateOrganizationRequest))]
[JsonSerializable(typeof(UpdateOrganizationRequest))]
[JsonSerializable(typeof(ConfigOptionDto))]
[JsonSerializable(typeof(ConfigOptionDto[]))]
[JsonSerializable(typeof(ReferenceCategoryDto))]
[JsonSerializable(typeof(ReferenceCategoryDto[]))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(VoiceReferenceDto))]
[JsonSerializable(typeof(VoiceReferenceDto[]))]
[JsonSerializable(typeof(AdminVoiceReferenceDto))]
[JsonSerializable(typeof(AdminVoiceReferenceDto[]))]
[JsonSerializable(typeof(UpsertVoiceReferenceRequest))]
[JsonSerializable(typeof(AdminFormOptionDto))]
[JsonSerializable(typeof(AdminFormOptionDto[]))]
[JsonSerializable(typeof(UpsertFormOptionRequest))]
[JsonSerializable(typeof(AdminFileCategoryDto))]
[JsonSerializable(typeof(AdminFileCategoryDto[]))]
[JsonSerializable(typeof(UpsertFileCategoryRequest))]


[JsonSerializable(typeof(FormOptionsDto))]
[JsonSerializable(typeof(ProjectInfoDto))]
[JsonSerializable(typeof(BookInfoDto))]
[JsonSerializable(typeof(CharacterInfoDto))]
[JsonSerializable(typeof(CharacterInfoDto[]))]
[JsonSerializable(typeof(CreativeInfoDto))]
[JsonSerializable(typeof(ReferenceAssetDto))]
[JsonSerializable(typeof(ReferenceAssetDto[]))]
[JsonSerializable(typeof(VoiceoverInfoDto))]
[JsonSerializable(typeof(CreativeDirectionDto))]
[JsonSerializable(typeof(VoiceAndReferencesInfoDto))]
[JsonSerializable(typeof(TaskDraftDto))]
[JsonSerializable(typeof(ProjectSummaryDto))]
[JsonSerializable(typeof(ProjectSummaryDto[]))]
[JsonSerializable(typeof(PagedProjectsDto))]
[JsonSerializable(typeof(AdminProjectSummaryDto))]
[JsonSerializable(typeof(AdminProjectSummaryDto[]))]
[JsonSerializable(typeof(PagedAdminProjectsDto))]
[JsonSerializable(typeof(AdminCountDto))]
[JsonSerializable(typeof(AdminCountDto[]))]
[JsonSerializable(typeof(AdminOverviewDto))]
[JsonSerializable(typeof(AuditEventDto))]
[JsonSerializable(typeof(AuditEventDto[]))]
[JsonSerializable(typeof(PagedAuditEventsDto))]
[JsonSerializable(typeof(AdminNoteDto))]
[JsonSerializable(typeof(AdminNoteDto[]))]
[JsonSerializable(typeof(AdminProjectDetailDto))]
[JsonSerializable(typeof(UpdateProjectWorkflowRequest))]
[JsonSerializable(typeof(AddAdminNoteRequest))]
[JsonSerializable(typeof(FinalDeliveryDto))]
[JsonSerializable(typeof(FinalDeliveryDto[]))]
[JsonSerializable(typeof(SaveDraftRequest))]
[JsonSerializable(typeof(SaveCreativeRequest))]
[JsonSerializable(typeof(SaveVoiceAndReferencesRequest))]
[JsonSerializable(typeof(ValidateProjectRequest))]
[JsonSerializable(typeof(ValidationResultDto))]
[JsonSerializable(typeof(SubmitProjectRequest))]
[JsonSerializable(typeof(UploadReferenceResultDto))]
[JsonSerializable(typeof(FieldErrorDto))]
[JsonSerializable(typeof(FieldErrorDto[]))]
[JsonSerializable(typeof(ApiErrorDto))]
internal partial class AppJsonContext : JsonSerializerContext;
