// @vitest-environment jsdom
import {act} from "react";
import {createRoot,type Root} from "react-dom/client";
import {createMemoryRouter,RouterProvider} from "react-router-dom";
import {beforeEach,afterEach,it,expect,vi} from "vitest";
import {invitationService} from "@lifewood/api-client";
import {i18n} from "@lifewood/i18n";
import {InvitationRegistrationPage} from "./pages/InvitationRegistrationPage";
(globalThis as typeof globalThis & {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root,host:HTMLDivElement,router:ReturnType<typeof createMemoryRouter>;
const settle=async()=>act(async()=>{await new Promise(r=>setTimeout(r,20));});
beforeEach(async()=>{const {transferableAbortController}=await vi.importActual<{transferableAbortController:()=>AbortController}>("node:util");vi.stubGlobal("AbortController",class{constructor(){return transferableAbortController();}});host=document.createElement("div");document.body.append(host);root=createRoot(host);vi.spyOn(invitationService,"lookup").mockResolvedValue({organization:"Demo team"});vi.spyOn(invitationService,"inspect").mockResolvedValue({organization:"Demo team",email:"member@example.com",displayName:"Saved nickname"});vi.spyOn(invitationService,"email").mockResolvedValue();vi.spyOn(invitationService,"register").mockResolvedValue();});
afterEach(async()=>{await act(async()=>root.unmount());router.dispose();host.remove();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function mount(locale:string,fragment=""){await i18n.changeLanguage(locale);router=createMemoryRouter([{path:"/:locale/register",element:<InvitationRegistrationPage/>},{path:"/:locale/login",element:<div/>}],{initialEntries:[`/${locale}/register${fragment}`]});await act(async()=>root.render(<RouterProvider router={router}/>));await settle();}
function fill(name:string,value:string){const input=host.querySelector<HTMLInputElement>(`input[name="${name}"]`)!;input.value=value;}
async function submit(){await act(async()=>{host.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));});await settle();}
for(const locale of ["zh-CN","en-US"]){
 it(`requires email proof before account creation (${locale})`,async()=>{await mount(locale);expect(host.querySelector('input[type="password"]')).toBeNull();expect(invitationService.register).not.toHaveBeenCalled();expect(host.textContent).toContain(i18n.t("invitation.register"));});
 it(`removes token from URL and checks passwords before completing (${locale})`,async()=>{const token="A".repeat(64);await mount(locale,`#token=${token}`);expect(router.state.location.hash).toBe("");expect(host.textContent).toContain("Demo team");expect(host.querySelector<HTMLInputElement>('input[name="name"]')!.value).toBe("Saved nickname");expect(host.querySelector<HTMLInputElement>('input[name="email"]')!.readOnly).toBe(true);fill("name","New member");fill("password","password-123");fill("confirmation","different-123");await submit();expect(invitationService.register).not.toHaveBeenCalled();expect(host.textContent).toContain(i18n.t("invitation.mismatch"));fill("confirmation","password-123");await submit();expect(invitationService.register).toHaveBeenCalledWith(token,"New member","password-123");expect(host.textContent).toContain(i18n.t("invitation.done"));expect(host.querySelector('input[type="password"]')).toBeNull();});
 it(`does not allow stale or revoked token registration (${locale})`,async()=>{vi.mocked(invitationService.inspect).mockRejectedValue(new Error("expired"));await mount(locale,"#token="+"A".repeat(64));expect(host.querySelector('input[type="password"]')).toBeNull();expect(host.querySelector("button[type=submit]")??host.querySelector("form button")).toHaveProperty("disabled",true);expect(invitationService.register).not.toHaveBeenCalled();});
}

it("collects identity together and sends it with verification before enabling registration",async()=>{await mount("zh-CN");fill("name","My nickname");fill("email","member@example.com");fill("code","ABCDEF");expect(host.querySelectorAll("input")).toHaveLength(3);expect(host.querySelector("button[type=button].registration-pending")).toHaveProperty("disabled",true);await submit();expect(invitationService.email).toHaveBeenCalledWith("ABCDEF","member@example.com","zh-CN","My nickname");expect(invitationService.register).not.toHaveBeenCalled();expect(host.querySelector<HTMLInputElement>('input[name="name"]')!.value).toBe("My nickname");});

for(const locale of ["zh-CN","en-US"]){
 it(`recovers from a failed verification without creating an account (${locale})`,async()=>{vi.mocked(invitationService.inspect).mockRejectedValue(new Error("expired"));await mount(locale,"#token="+"A".repeat(64));const restart=Array.from(host.querySelectorAll("button")).find(b=>b.textContent===i18n.t("invitation.restart"))!;await act(async()=>restart.click());expect(host.querySelector('input[name="code"]')).not.toBeNull();expect(host.querySelector<HTMLInputElement>('input[name="email"]')!.readOnly).toBe(false);expect(host.querySelector('[role="alert"]')).toBeNull();expect(invitationService.register).not.toHaveBeenCalled();});
 it(`shows both passwords and focuses mismatch (${locale})`,async()=>{await mount(locale,"#token="+"A".repeat(64));const toggle=host.querySelector<HTMLButtonElement>('button[aria-pressed]')!;await act(async()=>toggle.click());expect(host.querySelector<HTMLInputElement>('input[name="password"]')!.type).toBe("text");expect(host.querySelector<HTMLInputElement>('input[name="confirmation"]')!.type).toBe("text");fill("password","password-123");fill("confirmation","different-123");await submit();expect(document.activeElement).toBe(host.querySelector('input[name="confirmation"]'));expect(document.activeElement).toHaveProperty("ariaInvalid","true");await act(async()=>toggle.click());expect(host.querySelector<HTMLInputElement>('input[name="password"]')!.type).toBe("password");});
}

it("prefills a shared invitation code and removes it from the address bar",async()=>{await mount("zh-CN","#code=ABCDEF");expect(host.querySelector<HTMLInputElement>('input[name="code"]')!.value).toBe("ABCDEF");expect(router.state.location.hash).toBe("");expect(invitationService.email).not.toHaveBeenCalled();});
it("passes the verified email to login after successful registration",async()=>{await mount("en-US","#token="+"A".repeat(64));fill("password","password-123");fill("confirmation","password-123");await submit();await act(async()=>host.querySelector<HTMLAnchorElement>('a[href="/en-US/login"]')!.click());expect(router.state.location.state.registrationEmail).toBe("member@example.com");});
